server:
  port: 8081

#对象
student:
  name: qinjiang
  age: 3

#行内写法
student1: {name: qinjiang, age: 3}

# 数组
pets:
  -cat
  -dog
  -pig

pets1: [cat, dog, pig]

person:
  #name: qinjiang
  name: qinjiang${random.uuid}
  age: 3
  happy: false
  birth: 2019/11/01
  maps: {k1, k2, k3}
  lists:
    - code
    - music
    - girl
  dog:
    name: 旺财
    age: 3
