server:
  port: 8081


#对象
student:
  name: qinjiang
  age: 3

#行内写法
student1: {name: qinjiang, age: 3}

# 数组
pets:
  -cat
  -dog
  -pig

pets1: [cat, dog, pig]

person:
  #松散绑定：yml中写的last-name, 这个和lastName是一样的，- 后面跟着的字母默认是大写的
  last-name: qinjiang
  #name: qinjiang
  name: qinjiang${random.uuid}
  age: 3
  happy: false
  birth: 2019/11/01
  maps: {k1, k2, k3}
  #hello: happy
  lists:
    - code
    - music
    - girl
  dog:
    name: ${person.hello:hello}_旺财
    age: 3

# springboot的多环境配置，可以选择激活哪一个配置文件
spring:
  profiles:
    active: dev

---
server:
  port: 8021
spring:
  profiles: dev

---
server:
  port: 8022
spring:
  profiles: test
